<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>XMedius.SendSecure</RootNamespace>
    <AssemblyName>XMedius.SendSecure</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Test\**" />
    <None Remove="Test\**" />
  </ItemGroup>
  <!-- Source files are included by default in SDK-style projects. If you have special files, add them here. -->
</Project>