<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XMedius.SendSecure.csproj" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.2" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="app.config" />
  </ItemGroup>
</Project>